# Generated by Django 4.0.4 on 2022-05-11 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('chef_name', models.CharField(max_length=100)),
                ('chef_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('client_address', models.CharField(max_length=100)),
                ('client_phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('food_description', models.TextField(max_length=250)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='img/%y')),
                ('chef_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ch2', to='data.chef')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('ingredients_id', models.IntegerField()),
                ('ingredients_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ingredients_img', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='img/%y')),
                ('ingredients_validity', models.DateField()),
                ('ingredients_food_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ingredients', to='data.food')),
            ],
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('waiter_id', models.IntegerField(primary_key=True, serialize=False)),
                ('waiter_name', models.CharField(max_length=100)),
                ('waiter_price', models.IntegerField()),
                ('waiter_phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=100)),
                ('supplier_city', models.CharField(max_length=100)),
                ('supplier_phone', models.IntegerField()),
                ('supplier_price', models.IntegerField()),
                ('supplier_chef_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='su2', to='data.chef')),
            ],
        ),
        migrations.CreateModel(
            name='Provide',
            fields=[
                ('provides_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('provides_number', models.IntegerField()),
                ('data', models.DateField()),
                ('provides_ingredients_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Ingredients_name', to='data.ingredients')),
                ('provides_supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='provides', to='data.suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_id', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('orders_food', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='food', to='data.food')),
                ('orders_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to='data.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='client_waiter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer', to='data.waiter'),
        ),
    ]
