# Generated by Django 4.0.4 on 2022-05-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('client_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('client_address', models.CharField(max_length=100)),
                ('client_phone', models.IntegerField()),
                ('waiter_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Client',
            },
        ),
    ]
