# Generated by Django 4.0.4 on 2022-05-12 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orders_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to='data.clients'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
