# Generated by Django 4.0.4 on 2022-05-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_clients_waiter_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientsForBurger',
            fields=[
                ('ingredients_id', models.IntegerField()),
                ('ingredients_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ingredients_img', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='img/%y')),
                ('ingredients_validity', models.DateField()),
                ('ingredients_food_id', models.IntegerField()),
            ],
        ),
    ]
