# Generated by Django 4.0.4 on 2022-05-12 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_ingredientsforburger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provide',
            name='provides_ingredients_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Ingredients_name', to='data.ingredientsforburger'),
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
    ]
