# Generated by Django 4.0.4 on 2022-05-12 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_provide_provides_ingredients_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsforburger',
            name='ingredients_food_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ingredients', to='data.food'),
        ),
    ]
