# Generated by Django 4.0.2 on 2022-05-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_ingredientsforburger_ingredients_food_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiter',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='img/%y'),
        ),
    ]
